baseURL = "https://nanta-data.dev/"
defaultContentLanguage = "ko"
theme = "blowfish"
paginate = 10
enableRobotsTXT = true
enableEmoji = true
buildFuture = true

# googleAnalytics = "G-XXXXXXXXXX"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
